[project]
name = "list-of-ethnic-media"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "tldextract>=5.3.0",
]
